- id: wrapscallion
  name: wrapscallion
  description: Lint Conventional Commit messages and 72-column bodies.
  entry: ghcr.io/underwhelmingperformance/wrapscallion@sha256:3cdb422e06ce2926cf2cda1c0507fcdd39eb51f0c45b1ac367ed1813669e8b72 --output-format terminal --edit
  language: docker_image
  stages:
    - commit-msg
- id: wrapscallion-system
  name: wrapscallion (system Deno)
  description: Lint Conventional Commit messages using deno from PATH.
  entry: hooks/wrapscallion
  language: script
  stages:
    - commit-msg
